name: e2e tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  cypress-run:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Postgres
        run: docker run -d -e POSTGRES_DB=guillotina -e POSTGRES_USER=guillotina -e POSTGRES_HOST_AUTH_METHOD=trust -p 127.0.0.1:5532:5432 --name postgres postgres:12.17
      - name: Build guillotina
        run: docker build -t guillotina_e2e .
        working-directory: "guillotina_example/guillotina_react_app"
      - name: Run guillotina
        run: docker run -d --link=postgres -p 0.0.0.0:8080:8080 guillotina_e2e:latest

      - name: Install base modules and build dist
        run: yarn

      - name: Start Server
        run: npm install && npm run build && npm run preview &
        working-directory: e2e/vite_example

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm install
          wait-on: 'http://localhost:4173'
          working-directory: e2e

      - name: Artifacts
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: e2e/cypress/videos