applications:
  - guillotina.contrib.dbusers
  - guillotina.contrib.catalog.pg
  - guillotina.contrib.swagger
  - guillotina.contrib.dyncontent
databases:
  db:
    storage: postgresql
    dsn: postgres://guillotina:guillotina@postgres_guillotina_react/guillotina
    read_only: false
    cache_strategy: redis
    autovacuum: true
    db_schema: guillotina
    pool_size: 8
host: 0.0.0.0
port: 8080
root_user:
  password: root
auth_extractors:
  - guillotina.auth.extractors.BearerAuthPolicy
  - guillotina.auth.extractors.BasicAuthPolicy
  - guillotina.auth.extractors.WSTokenAuthPolicy
auth_token_validators:
  - guillotina.auth.validators.SaltedHashPasswordValidator
  - guillotina.auth.validators.JWTValidator
cors:
  allow_origin:
    - '*' # delegate to reverse proxy whichs domains to allow
  allow_methods:
    - GET
    - POST
    - DELETE
    - HEAD
    - PATCH
    - PUT
    - OPTIONS
  allow_headers:
    - '*'
  expose_headers:
    - '*'
  allow_credentials: true
  max_age: 3660
jwt:
  secret: secret
  algorithm: HS256
loop_policy: uvloop.EventLoopPolicy
redis:
  host: redis
  port: 6379
  ttl: 3600
  memory_cache_size: 104857600 # 100 MB
  pool:
    minsize: 5
    maxsize: 10


contents:
  GMI:
    title: GMI title
    inherited_interface: guillotina.interfaces.IFolder
    inherited_class: guillotina.content.Folder
    add_permission: guillotina.AddContent
    allowed_types: 
      - Image
      - File
    behaviors:
      - guillotina.behaviors.dublincore.IDublinCore
    properties:
      json_example:
        type: guillotina.schema.JSONField
        schema: 
          title: My Json Field
          type: object
          properties:
            items:
              type: array
      text_richtext_field:
        type: guillotina.schema.Text
        widget: richtext
        title: Text richtext field
        index:
          type: searchabletext
          required: true
      text_field:
        type: guillotina.schema.Text
        title: Text field
        index:
          type: searchabletext
      text_line_field:
        type: guillotina.schema.TextLine
        title: Text line field
      number_field:
        type: guillotina.schema.Int
        title: Number field
        required: true
      choice_field:
        type: guillotina.schema.Choice
        title: Choice field
        required: true
        vocabulary: 
          plone: Plone text
          guillotina: Guillotina text
      boolean_field:
        type: guillotina.schema.Bool
        title: Boolean field
      cloud_file_field: 
        type: guillotina.fields.CloudFileField
        title: Cloud file field
      list_field:
        type: guillotina.schema.List
        missing_value: []
        value_type: guillotina.schema.TextLine
        title: List field
      datetime_field:
        type: guillotina.schema.Datetime
        title: Datetime field



